// Emits the liquidity-duration grid of the paper (paper/tex, Table 2) as LaTeX rows.
// Run: node --experimental-strip-types model/grid.ts > paper/tex/grid.tex
// Every number in that table comes from here; nothing is hand-edited.

import { runCorner, type CornerParams } from "./server.ts";

const trailing = { kind: "trailing", intervalBlocks: 4032, roundBlocks: 6 } as const;
const oracle = { kind: "oracle" } as const;

const many = (over: Partial<CornerParams>): CornerParams => ({
  agents: 200, horizonLifetimes: 8, driftPerRound: 0, burst: { vIn: 5000, vOut: 4000, pIn: 0.02 },
  margin: 0.25, forecast: trailing, volume: "both", serverTier: true, seed: 1, ...over,
});
const few = (over: Partial<CornerParams>): CornerParams => ({
  agents: 3, horizonLifetimes: 8, driftPerRound: 0, burst: { vIn: 0, vOut: 1, pIn: 0 }, steady: { base: 100, jitter: 10 },
  margin: 0.25, forecast: trailing, volume: "both", serverTier: true, seed: 2, ...over,
});

const cells: Array<[string, CornerParams]> = [
  ["200 agents, bursty, drift $0$, $H=8\\tau$", many({})],
  ["200 agents, bursty, drift $0$, $H=1\\tau$", many({ horizonLifetimes: 1 })],
  ["200 agents, bursty, drift $+60$, $H=8\\tau$", many({ driftPerRound: 60 })],
  ["200 agents, bursty, drift $-30$, $H=8\\tau$", many({ driftPerRound: -30 })],
  ["3 agents, steady, drift $0$, $H=8\\tau$", few({})],
];

const f = (x: number) => (Number.isFinite(x) ? x.toFixed(2) : "$\\infty$");
const lines: string[] = [];
for (const [label, base] of cells) {
  const r = (over: Partial<CornerParams>) => runCorner({ ...base, ...over }).ratio;
  lines.push(
    `${label} & ${f(r({ spendLock: "expiry", forecast: oracle }))} & ${f(r({ spendLock: "expiry", forecast: trailing }))}` +
      ` & ${f(r({ spendLock: "round", forecast: oracle }))} & ${f(r({ spendLock: "round", forecast: trailing }))} \\\\`,
  );
}
// Accounting-only variants of the drift corner: what the earlier harness reported and why.
const drift = many({ driftPerRound: 60, forecast: oracle, spendLock: "expiry" });
const acct = [
  ["no server-tier term, outbound-only volume", runCorner({ ...drift, serverTier: false, volume: "out" }).ratio],
  ["no server-tier term, two-way volume", runCorner({ ...drift, serverTier: false }).ratio],
  ["server-tier term charged, two-way volume", runCorner(drift).ratio],
] as const;
process.stdout.write("% generated by model/grid.ts; do not edit\n");
process.stdout.write("\\newcommand{\\gridrows}{%\n" + lines.join("\n") + "}\n");
process.stdout.write("\\newcommand{\\acctrows}{%\n" + acct.map(([l, v]) => `${l} & ${f(v)} \\\\`).join("\n") + "}\n");
